"""add locality metadata

Revision ID: 264fd480b35a
Revises: 4a9e63c7fa5d
Create Date: 2026-09-29 14:18:32.213838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '264fd480b35a'
down_revision: Union[str, Sequence[str], None] = '4a9e63c7fa5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localities', sa.Column('siruta_sup', sa.Integer(), nullable=True))
    op.add_column('localities', sa.Column('locality_type', sa.String(length=200), nullable=True))
    op.add_column('localities', sa.Column('population', sa.Integer(), nullable=True))
    op.alter_column('localities', 'siruta',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('localities', 'siruta',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('localities', 'population')
    op.drop_column('localities', 'locality_type')
    op.drop_column('localities', 'siruta_sup')
    # ### end Alembic commands ###
