"""add siruta to localities

Revision ID: 4a9e63c7fa5d
Revises: 5be1a4b7c469
Create Date: 2026-09-29 13:53:32.693401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9e63c7fa5d'
down_revision: Union[str, Sequence[str], None] = '5be1a4b7c469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('localities', sa.Column('siruta', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_localities_siruta'), 'localities', ['siruta'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localities_siruta'), table_name='localities')
    op.drop_column('localities', 'siruta')
    # ### end Alembic commands ###
